### ISSUE TITLE
via conflict with embed at http://biostor.org/reference/145822/page/16 in chrome

### ISSUE THREAD

**Issue by judell** [hypothesis/via#40] opened 2015-09-09 21:28 UTC
The error that seems to prevent annotations from anchoring:

Unhandled promise rejection DOMException: Failed to execute 'postMessage' on 'Window': An object could not be cloned.(…)

**Comment by ikreymer** [comment] 2015-09-09 21:50
Hmm.. this is a postMessage() from the hypothesis code somewhere.. not sure where to look.. maybe should try w/ non-minified version..

**Comment by tilgovi** [comment] 2015-09-09 22:14
Is Biostor open source? Can we run it locally?

**Comment by judell** [comment] 2015-09-10 00:03
https://github.com/rdmpage/biostor-annotations

**Comment by ikreymer** [comment] 2015-09-10 21:28
FWIW.. It appears that this is also caused by the `href = "."` polyfill, related to #41 

I think what happens is that the actual exception message, related to invalid URL, gets passed in as an argument to postMessage, thus causing a different exception

**Comment by ikreymer** [comment] 2015-09-10 21:31
Hmm, actually, here it looks like the value of `document.baseURI` is `http://` .. looking into it further..

**Comment by tilgovi** [comment] 2015-09-10 22:25
I just did this: https://github.com/hypothesis/h/commit/0dee222385abcbc2138803ca120427ef0a8409f9

**Comment by tilgovi** [comment] 2015-09-10 22:44
This one is now fixed.

**Comment by tilgovi** [comment] 2015-09-10 22:44
Err, oops. Wrong one.

**Comment by tilgovi** [comment] 2015-09-10 22:44
Something more than the base-uri is going on, maybe?

**Comment by tilgovi** [comment] 2015-09-10 22:49
Okay, so now this is squarely within the scope of via to fix.

The original page has a base tag with an absolute URL to the biostor base URL.
The via page has a base tag with the URL "http:///".

Seems to be a problem rewriting the base tag, maybe?

**Comment by ikreymer** [comment] 2015-09-10 23:12
Yes, in `config.yaml`, comment out `rewrite_base: false` that is no longer needed:

http://pywb-h.herokuapp.com/http://biostor.org/reference/145822/page/16

(I am also working on general solution for `a.href = "."` and no / as it may come up again on other sites...)

**Comment by tilgovi** [comment] 2015-09-10 23:22
I switched to a new shim of my own so I don't think that should be a problem anymore.

**Comment by tilgovi** [comment] 2015-09-10 23:34
Alright, we're good. Deployed.

**Closed by tilgovi** 2015-09-10 23:34 UTC
