### ISSUE TITLE
Change the Via HTML AWS NGINX to allow larger headers

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/via#250] opened 2020-08-25 15:24 UTC
This fixes sites like youtube.com that send very large headers. We do this in the deployed NGINX, but not the Elastic Beanstalk one.

In our code this is something like:

```            
# Prevent enormous headers (like youtube sends back) from killing
# us. This prevents "upstream sent too big header while reading
# response header from upstream" errors in our output
uwsgi_buffer_size          128k;
uwsgi_buffers              4 256k;
uwsgi_busy_buffers_size    256k;
```

For the external NGINX it would probably be `proxy_...` instead of `uwsgi_...`.

### Questions

 * Is this actually what's going on at all?
 * Can we configure this at all?
 * If we can where's the best place to do it?

### Replication:

 * https://qa-via3.hypothes.is/html/v/https://twitter.com/JesseLehrich/status/1282089662023176192/photo/1

Results in the following logging:

```
Sept 07 17:37:57 via3-prod_i-04fc25cf0231eb866 error.log 2020/09/07 16:37:57 [error] 4698#0: *640 upstream sent too big header while reading response header from upstream, client: 10.1.5.37, server: , request: "GET /html/v/https://twitter.com/JesseLehrich/status/1282089662023176192/photo/1 HTTP/1.1", upstream: "http://172.17.0.2:9083/html/v/https://twitter.com/JesseLehrich/status/1282089662023176192/photo/1", host: "via3.hypothes.is", referrer: "https://via3.hypothes.is/html/v/https://t.co/zyNoimdvTl"
```

**Comment by indigobravo** [comment] 2020-08-26 15:39
@jon-betts - When you get a moment, can you please devise a method to test this problem. We can then run the test before and after any changes are made to verify if a fix has been implemented.

**Comment by indigobravo** [comment] 2020-08-26 15:40
Due to be working on this the week starting: 2020-09-07

**Comment by indigobravo** [comment] 2020-09-17 14:15
Work here is now complete. I can load the following Prod and QA urls with hitting a 502 error.

https://via3.hypothes.is/html/v/https://twitter.com/JesseLehrich/status/1282089662023176192/photo/1
https://qa-via3.hypothes.is/html/v/https://twitter.com/JesseLehrich/status/1282089662023176192/photo/1

A couple of points to note...

**Memory consumption**
I am not sure we can provide a finer grained solution without testing the header size of all the sites we are likely to proxy, which could also change over time anyway. Due to this, we might get into the situation where Via uses more memory than it previously use to. It also means we are vastly overspec for the majority of sites we will be working with.

The settings applied mean we will use 640K of RAM for each connection we are proxy. It will soon add up if we are serving many connections at the same time. Some rough sums....

1000 connections = 6.4GB
2000 connections = 12.8GB
3000 connections = 19.2GB
4000 connections = 25.6GB

**Container Commands**
Elastic Beanstalk is doing something funny when it attempts to validate an nginx config. I don't know exactly what it is doing, but if you define a command to reload nginx after the ebextension has run via the container commands method. The deployment will potentially fail.

I have only been able to cause it to fail in production, it completes successfully in qa. This may have something to do with the deployment types with prod doing a rolling / immutable update, and qa doing it in place. I am not sure...

However, what I can confirm is you don't need to perform the reload via the ebextension. Elastic Beanstalk performs an nginx restart after the deployment has completed successfully, so it removes the need to perform the reload via the extension.

Others have reported similar problems. The stackoverflow post here, provides a response from AWS support: https://stackoverflow.com/a/48203336/434243

Links to PRs with additional commentary...

https://github.com/hypothesis/deployment/pull/130
https://github.com/hypothesis/deployment/pull/133

**Closed as completed by indigobravo** 2020-09-17 14:15 UTC
Labels: bug, Operations
