### ISSUE TITLE
via fails (in edge) for https://medium.com/@joshelman/four-questions-to-understanding-adoption-8fc499910e8a

### ISSUE THREAD

**Issue by judell** [hypothesis/via#48] opened 2015-09-22 03:30 UTC
SCRIPT5007: Unable to get property 'call' of undefined or null reference
wombat.js (728,13)

**Comment by nickstenning** [comment] 2015-10-14 13:31
I can't reproduce this. Perhaps fixed by recent changes to pywb.

**Comment by nickstenning** [comment] 2015-10-14 13:35
Oh, I just noticed the title said in the Edge browser, which I don't have an easy means of checking.

**Comment by judell** [comment] 2015-10-14 18:14
Rechecked in Edge on a new machine. Similar message which traces to what's now line 763 in wombat.js:

        var get_baseURI = function() {
            var res = orig_getter.call(this);   <- this line
            return extract_orig(res);
        }

**Closed** 2015-11-30 10:48 UTC
