### ISSUE TITLE
User gets a 403 error when trying to load an LMS Google picker assignment

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/via#136] opened 2020-04-01 19:54 UTC
**Describe the bug**
Intermittently, users will get the following when trying to open an assignment made with a PDF in Drive:
>Unexpected server response (403) while retrieving PDF "https://via3.hypothesis.is/proxy/static/...

The network response was:
`<html><head><meta http-equiv=“content-type” content=“text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style=“text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%“><div style=“border-bottom: 1px solid #DFDFDF;“>Sorry...</div></td></tr></table></div><div style=“margin-left: 4em;“><h1>We’re sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can’t process your request right now.</p></div><div style=“margin-left: 4em;“>See <a href=“https://support.google.com/websearch/answer/86640”>Google Help</a> for more information.<br/><br/></div><div style=“text-align: center; border-top: 1px solid`

**To Reproduce**
This bug seems to be intermittent, and is not reliable to reproduce.
1. Log in to Canvas as an instructor and create an Assignment using a PDF in GDrive.
2. Open the assignment periodically until you get the above error.

**Expected behavior**
The PDF should open like other Drive-integrated assignments, with the PDF visible in pdf.js, and the Hypothesis Sidebar present.

**Screenshots**
Error:
![image](https://user-images.githubusercontent.com/22603275/78180254-83666700-7430-11ea-965a-b1d7aafb3ea3.png)

Netword response:
![image](https://user-images.githubusercontent.com/22603275/78180288-8feabf80-7430-11ea-8968-50265d6d3af6.png)

Console error 1:
![image](https://user-images.githubusercontent.com/22603275/78180360-b01a7e80-7430-11ea-8353-b3065927eb77.png)

Console error 2:
![image](https://user-images.githubusercontent.com/22603275/78180405-bdd00400-7430-11ea-9f85-231a045662f9.png)

**Additional context**
Slack convo:
https://hypothes-is.slack.com/archives/CBN3DGW02/p1585598606033800

**Comment by jon-betts** [comment] 2020-04-09 18:02
A fix for this has been deployed as far as QA and testing / thinking and getting more familiar with Google API console has revealed some details.

* Google has quotas, this means this is likely to fix our issues as long as we stay within them
* This change allows us to make much more effective use of Cloudflare caching (meaning fewer requests and much faster loading for most users)
* The API route does not return detailed filename information, so the filename is blank, causing the page title to become just "uc"

**Why our caching should be better**

Previously when asking for us to proxy Google docs the following would happen:

 * You go to: `..via3/proxy/static/<google doc url>`
 * NGINX goes to `<google doc url>`
 * `<google doc url>` returns a redirect, which we cannot cache to `<final doc url>`
 * NGINX redirects the user to `..via3/proxy/static/<final doc url>`
 * User starts over going to `..via3/proxy/static/<final doc url>`
 * NGINX goes to `<final doc url>`
 * NGINX returns the document

You can't cache the redirect at all, because the second final location could be user/region specific. We should cache the second, but it's less likely. A casual test suggests we're not / not consistently.

In the new world:

 * You go to: `..via3/proxy/static/<google doc url>`
 * NGINX goes to `<google API url>`
 * NGINX returns the document

This can be cached right away

**Comment by jon-betts** [comment] 2020-04-09 18:05
An informal test suggests the redirects above are different for different users.

**Comment by jon-betts** [comment] 2020-04-16 10:36
It looks like the fix has resolved the issue, and we aren't using much of our alloted quota (<1%), so I think we're good here. @mkdir-washington-edu do you think we're good to close this?

**Comment by jon-betts** [comment] 2020-04-17 12:32
Just confirmed in chat this is good to close

**Closed as completed** 2020-04-17 12:32 UTC
Labels: bug
