### ISSUE TITLE
pip install errors

### ISSUE THREAD

**Issue by BigBlueHat** [hypothesis/via#27] opened 2015-07-28 16:00 UTC
When doing `pip install -r requirements.txt` I get these errors:

On Mac OS X 10.6.8:
```
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -O3 -Wall -Wstrict-prototypes -DWATCHDOG_VERSION_STRING="0.8.3" -DWATCHDOG_VERSION_MAJOR=0 -DWATCHDOG_VERSION_MINOR=8 -DWATCHDOG_VERSION_BUILD=3 -I/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/watchdog_fsevents.c -o build/temp.macosx-10.6-x86_64-2.7/src/watchdog_fsevents.o -std=c99 -pedantic -Wall -Wextra -fPIC -Wno-error=unused-command-line-argument-hard-error-in-future

cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future

error: command 'gcc-4.2' failed with exit status 1

----------------------------------------
Cleaning up...
Command /Users/byoung/.virtualenvs/via/bin/python -c "import setuptools, tokenize;__file__='/Users/byoung/.virtualenvs/via/build/watchdog/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/z+/z+cc9iByHBS08J1CIk0G4U+++TI/-Tmp-/pip-yZuY1E-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/byoung/.virtualenvs/via/bin/../include/site/python2.7 failed with error code 1 in /Users/byoung/.virtualenvs/via/build/watchdog
Traceback (most recent call last):
  File "/Users/byoung/.virtualenvs/via/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/Users/byoung/.virtualenvs/via/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/Users/byoung/.virtualenvs/via/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 30: ordinal not in range(128)
```

and on Windows 8.1
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\benjamin\appdata\local\temp\pip-build-dxwb5b\uwsgi\setup.py", line 3, in <module>
        import uwsgiconfig as uc
      File "uwsgiconfig.py", line 8, in <module>
        uwsgi_os = os.uname()[0]
    AttributeError: 'module' object has no attribute 'uname'

    ----------------------------------------
←[31mCommand "python setup.py egg_info" failed with error code 1 in c:\users\benjamin\appdata\local\temp\pip-build-dxwb5b\uwsgi←[0m
```

Pretty sure these are "not our problem" but it's something I'm seeing which is currently blocking me contributing and testing via locally (fwiw).

I'll be digging into these next time I need to dig into via, but if someone knows how to fix these sooner, I'm all :ear:s.

**Comment by tilgovi** [comment] 2015-07-28 21:23
Check this for macos: http://stackoverflow.com/questions/27740044/pip-cffi-package-installation-falied-on-osx

**Comment by tilgovi** [comment] 2015-07-28 21:24
`uname` just isn't supported on windows. You may not be able to use uwsgi, except experimentally with cygwin: http://uwsgi-docs.readthedocs.org/en/latest/Changelog-1.9.html#cygwin-windows-support

**Comment by ikreymer** [comment] 2015-07-28 21:27
Yeah, uwsgi is not supported on windows, however, pywb/via doesn't require uwsgi.. Should there be a different WSGI container for windows?

For MacOS, yeah, I think probably caused by an older version of gcc...

**Comment by tilgovi** [comment] 2015-07-28 22:02
`wsgiref` or `waitress` should work fine for Windows. Not for production use.

**Comment by BigBlueHat** [comment] 2015-07-29 15:39
Great to know. Thanks! :+1:  I'll write up how I fix it when I fix it.

**Comment by nickstenning** [comment] 2015-11-30 13:32
Via is now built and runs inside a Docker container. Closing.

**Closed by nickstenning** 2015-11-30 13:32 UTC
